### ISSUE TITLE
TRex version

### ISSUE THREAD

**Issue by apconole** [chaudron/ovs_perf#28]
Should we specify a trex version?  v2.53 seems to work, and it might make sense to run that rather than recommending an older version.

**Comment by chaudron** [comment]
I think currently it's v2.29 due to the change in the python API layout. So the instructions will not work with v2.53. I guess a couple of releases after v2.29 it changed.

I'll try to rework the script and instructions ASAP so it will work with the latest release, and we once verified we can reset the base version to this.

**Comment by chaudron** [comment]
Fixed with #29
